### ISSUE TITLE
GTK-free makefile

### ISSUE THREAD

**Issue by Light2Yellow** [majn/telegram-purple#100]
In your makefile you assume that .../pidgin folder should exist, but I don't think it is the right way this should be handled. A KDE user will hardly ever install pidgin, so please provide a checker (does this folder exist or is pidgin installed) and push pidgin icons only if needed.

**Comment by BenWiederhake** [comment]
Everything else in the Makefile is frontend-agnostic, so you're right, this is something that should be fixed. Currently, it paths like this (I collapsed some macros by hand):

    `pkg-config --variable=datarootdir purple`/pixmaps/pidgin/protocols/16/telegram.png

Finch users (text-based, so the icon can't be displayed at all) might complain about those 9 or so inodes (3 for the files, 3 for each subdir, and 3 for each level of `pixmaps/pidgin/protocols`). For that, we could add a new option `--disable-pidgin-icons`

So this is what we're going to do, since you shouldn't be using telegram-purple with libtelepathy clients anymore: Use [telepathy-morse](https://akulichalexandr.wordpress.com/2015/03/24/telegram-connection-manager-the-first-release-is-going-on/), a native telepathy plugin.

**Comment by BenWiederhake** [comment]
Uhh ... this is a deeper problem. `make local_install` is very broken: See #100  telegram-purple expects the public key in a folder where only root can write (`/etc` has permissions `drwxr-xr-x root root`). It would take little but non-trivial effort to make `local_install` work.

However, it looks like nobody ever needed it, so I'm in favor of dropping that feature completely.

**Comment by Light2Yellow** [comment]
Thanks for your reply and for an advice too. As the issue is fixed, I'm closing it.

**Comment by BenWiederhake** [comment]
Reopening, as it's not yet merged with the development branch -- and especially not master.

**Comment by BenWiederhake** [comment]
(Don't worry, GitHub will automatically close this once that has happened.)

**Comment by Light2Yellow** [comment]
Ok, sorry. I'm just very new to Github, to git and to it's ecosystem at all :)
So, you've committed in your own copy of repo as it acts like draft version/branch?

**Comment by BenWiederhake** [comment]
Something like it. I hope we can soon merge out development branches, then the ["inventory"}(http://www.joelonsoftware.com/items/2012/07/09.html) finally goes down. Sorry for the delay :(

**Comment by BenWiederhake** [comment]
Please note that this feature will be destructively changed in 8bfed071563018cda55097fc33c860a396446c7c

If you are using this feature, please change your build scripts from:

    ./configure --disable-icons
    make install

to:

    ./configure
    make noicon_install

The flag `--disable-icons` will throw an error in the new version, in order to make sure every packager relying on the old form notices.
