### ISSUE TITLE
File transfer in Pidgin produces empty file

### ISSUE THREAD

**Issue by tuxmaster** [majn/telegram-purple#104]
Hello, when I received an file via secret chat the data will transporded, but the file on the disk are  every time 0 bytes.
Here the debug output of pidgin:
21:59:15) prpl-telegram: tgprpl_xfer_recv_init
(21:59:15) prpl-telegram: who: XXXXX
(21:59:16) prpl-telegram: PURPLE_XFER_RECEIVE progress 6 / 1628394
(21:59:16) prpl-telegram: PURPLE_XFER_RECEIVE progress 6 / 1628394
(21:59:16) prpl-telegram: PURPLE_XFER_RECEIVE progress 32774 / 1628394
(21:59:16) prpl-telegram: PURPLE_XFER_RECEIVE progress 49158 / 1628394
(21:59:16) prpl-telegram: PURPLE_XFER_RECEIVE progress 81926 / 1628394
...
(21:59:23) prpl-telegram: PURPLE_XFER_RECEIVE progress 1622022 / 1628394
(21:59:23) prpl-telegram: tgprpl_xfer_recv_on_finished()
(21:59:23) prpl-telegram: purple_xfer_set_completed

**Comment by tuxmaster** [comment]
Same happened on normal chats.

**Comment by majn** [comment]
This is an issue that only seems to occur in Pidgin and for all chat types

**Comment by nhermosilla14** [comment]
I've verified and it still happens using the latest code, but the files are actually received. The problem really is about renaming the file, because if you look for a file with an ugly (a really non-displayable, ugly name) in your home folder, there it will be. And if you try to open it with the proper app, you'll notice that it is the same file that should have the name that the other one, zero-sized file has.

**Comment by majn** [comment]
fixed
