### ISSUE TITLE
Group chats don't show member names

### ISSUE THREAD

**Issue by ShinzJr** [majn/telegram-purple#110]
![screenshot from 2015-09-01 15 16 47](https://cloud.githubusercontent.com/assets/7479638/9600420/32984d68-50c5-11e5-8f0b-a0ec82e38a1e.png)

**Comment by majn** [comment]
You need to add the members to your buddy list and their Alias (Real Name) will be displayed. The current version will only add contacts from your dialogue list.

**Comment by majn** [comment]
I should probably still add the chat members manually in that case to prevent confusion.

**Comment by EionRobb** [comment]
There's a couple of hacks you can do to set an alias on a chat buddy who is not in the buddy list (I do it in the ning plugin, for example)

**Comment by majn** [comment]
@EionRobb your solution works great, thanks for the hint. Saved me a lot of trouble.

**Comment by EionRobb** [comment]
Doesn't work in purple3 though :(

**Comment by majn** [comment]
@EionRobb 
I've already been thinking of migrating the buddy management to something that uses human-readable print names as buddy usernames, since it would solve tons of related issues. All other Telegram-Clients don't really expose the UID in any way in the interface (unlike in other protocolls like ICQ) but right now I'm kind of forced to confront the user with UIDs.

- Adium group chats containing the user ID instead of the user alias even if the buddy is added
- User autocompletion will display UIDs
- Foreign Buddies (not in the contact list) will only have the UID 

I could still store telegram UID as an integer in the blist nodes to handle name changes properly. Libtgl already provides unique user print-names so username collisions shouldn't be an issue. Do you think this would be a good solution for this from the libpurple-perspective?

**Comment by fauno** [comment]
:+1:  to show names, it's really awkward with big groups

**Comment by fauno** [comment]
i mean, i don't even see my name...

**Comment by majn** [comment]
fixed in v1.2.1
