### ISSUE TITLE
Add gettext support

### ISSUE THREAD

**Issue by tuxmaster** [majn/telegram-purple#114]
So that translation will be possible.

**Comment by BenWiederhake** [comment]
This will need to be a configure option, and will probably have to be solved like the `--disable-icons` thing, so that the `for polang in $(shell cat po/LINGUAS); do` stuff in the Makefile is skipped.

Dear reader: Do you really want that feature? It clutters the rest of the Makefile, so until someone actually needs this feature, we probably won't implement it.

**Comment by majn** [comment]
Translation was added in 1.2.2
