### ISSUE TITLE
Changing group chat title causes orphan logs

### ISSUE THREAD

**Issue by PabloCastellano** [majn/telegram-purple#15]
While individual chat logs are written to:
 ~/.purple/logs/telegram/"MY_CELL_NUMBER"/"ID"/*.txt,
group chat logs are written:
~/.purple/logs/telegram/"MY_CELL_NUMBER"/"GROUP_TITLE"/*.txt

Changing the group chat title doesn't rename the folder, so the old title logs remain unlinked to any chat.
The solution is not as easy as renaming the folder when the title changes as two group chats with the same title share the same folder and it would mess it up even more. Maybe using an uuid or using group title + uuid as folder?

**Comment by franciscod** [comment]
I think the directory name being an UUID makes sense.

Because this name isn't really meaningful to a human looking for its chats, there should be a way for mapping names to UUIDS. Maybe a text file containing current and old names is useful, something along these lines:

```
Current group UUIDs:

School Buddies: ADJIOIJWQEASKD-1231
Next meetup: 04-04!: IQWOPEIEWQOP-666

Old Names:
Next meetup: 03-03, woohoo!: IQWOPEIEWQOP-666
```

**Comment by majn** [comment]
@franciscod  Hey, Telegram already assigns unique IDs to all chats, and I already use those as a chat id in libpurple and the chat name as subject.

I think its because Libpurple will always use the displayed conversation name to store chat logs. The only fix I can think of at the moment would be to just not update the chat names after adding them for the first time.

**Comment by majn** [comment]
>The only fix I can think of at the moment would be to just not update the chat names after adding them for the first time.
This is how I do it now, btw.
