### ISSUE TITLE
Translations of the AppStream file

### ISSUE THREAD

**Issue by BenWiederhake** [majn/telegram-purple#211]
Please note that the topic has completely changed. This discussion started as "List frontends in AppStream file"

-----

Currently, `telegram-purple.metainfo.xml` has [very little meaning](https://github.com/majn/telegram-purple/pull/145#issuecomment-169060418) and only really contains `<extends>pidgin.desktop</extends>` and that's it.

We should start to insert more `<extends/>`-Tags, so let's collect some frontends so that the next version of telegram-purple doesn't look like it's pidgin-specific.

I'll start collecting the AppStream-IDs for the most obvious frontends/adaptors, but you're very welcome to help me with finding other frontends/adaptors or finding their IDs:

- pidgin ([id `pidgin.desktop`](https://hg.pidgin.im/pidgin/main/file/93ca6095dbe6/pidgin/data/pidgin.appdata.xml.in), already on the list)
- libtelepathy-haze ([has no ID](https://secure.freedesktop.org/cgit/telepathy/), not on the list)
- finch ([has no ID](https://hg.pidgin.im/pidgin/main/file/93ca6095dbe6/finch), not on the list)
- adium (has no ID, not on the list)
- spectrum2 ([has no ID](https://github.com/hanzz/spectrum2), not on the list)
- bitlbee ([has no ID](https://github.com/bitlbee/bitlbee), not on the list)
- libpurple itself (has no ID (even though pidgin does!?), not on the list)

**Comment by Sesivany** [comment]
libtelepathy-haze - it's not an app, so it's not covered by AppStream, it can possibly extend telepathy-based clients such as Empathy, KDE Telepathy, but then you'd have to install both libtelepathy-haze and purple-telegram, I'm not sure how AppStream could handle this case of chain dependecies.
finch - it's not GUI app, at least in Fedora we only include GUI apps now, it may change in the future, but currently no CLI apps ship appdata files in Fedora.
adium - not a Linux app, AppStream currently only covers Linux, possibly BSD.
spectrum2 - not an app
bitlbee - the same case as finch, not a GUI app

Pidgin is currently the only one you can include in <extends/>. Empathy also has an appdata file, but if you extended it, user would click the Telegram plugin and it would trigger an installation of purple-telegram package which doesn't have a dependency on libtelepathy-haze which wouldn't be pulled in the installation and Telegram wouldn't work for the user. AppStream is not replacing the packaging system, it only points a package manager to a package it should install, depedencies are still defined in packages.
It would make sense for CLI apps such as finch or bitlbee, but as I said Fedora has a rule that we only include GUI apps in the catalog, someone who wants to install a CLI app is expected to efficiently work with a package manager, so we don't ship any appdata for them and  don't push it upstream. Dunno about rules in other distributions, but since Fedora is pioneering this I think others just take what's there and the situation is the same.

But what we can improve in the metadata file are translations. AppStream metadata files can be translated. Most apps and plugins don't do it because it requires hooking it to a localization system, but it would definitely improve user experience.

**Comment by BenWiederhake** [comment]
> [...] at least in Fedora we only include GUI apps now, [...]
> adium - not a Linux app, AppStream currently only covers Linux, possibly BSD

So much for "cross-distribution" :/
But I understand those issues, they make sense.

Empathy and other libtelepathy actually shouldn't appear, because there's already telepathy-morse providing the Telegram support.

Translations: Oomph. A lot of work for around two strings. I'll look into how the Transifex support for this looks like. I don't think they support AppStream already :P

**Comment by EionRobb** [comment]
OT: it's a shame that InstantBird can't load libpurple plugins

**Comment by BenWiederhake** [comment]
This is a "translated" version with English, German, and a silly interpretation of "Klingon", auto-generated by my current version (not in majn's repo). Does this look okay to you? `appstream validate-strict` says it's OK.

	<?xml version="1.0" encoding="utf-8"?>
	
	<component type="addon">
		<id>telegram-purple</id>
		<extends>pidgin.desktop</extends>
		<name>Telegram</name>
		<name xml:lang="de">Telegram</name>
		<name xml:lang="tlh">Telegraaargh!</name>
		<summary>A plugin that adds support for Telegram</summary>
		<summary xml:lang="de">Plugin zur Unterstützung von Telegram</summary>
		<summary xml:lang="tlh">Support! Telegram! AAARGH!!!</summary>
		<url type="homepage">https://github.com/majn/telegram-purple</url>
		<url type="bugtracker">https://github.com/majn/telegram-purple/issues/</url>
		<metadata_license>GFDL-1.3</metadata_license>
		<project_license>GPL-2.0+</project_license>
		<updatecontact>eischmann_at_redhat.com</updatecontact>
	</component>

Unless someone vetoes this, it will be merged into dev-1.3.0 soon-ish.

**Comment by Sesivany** [comment]
Seems OK to me, can't wait to translate it to Czech :)

**Comment by BenWiederhake** [comment]
Just for the record: [I hate the guy who decided to deviate from a well-defined, old, and perfectly working stadard, and didn't even give a rationale for that.](http://www.opentag.com/xfaq_lang.htm#lang_xmllangvalues)

**Comment by rodneyrod** [comment]
@EionRobb I thought that Instantbird could make use of libpurple plugins with minimal refactoring, since it still uses libpurple for the majority of its protocol support.

**Comment by BenWiederhake** [comment]
@rodneyrod Are you sure you clicked the right issue?  I don't see any connection ;)

**Comment by rodneyrod** [comment]
Replying to an earlier comment
