### ISSUE TITLE
Pidgin with telegram-purple crashes after disconnecting from network

### ISSUE THREAD

**Issue by Sesivany** [majn/telegram-purple#215]
Pidgin with telegram-purple 1.2.4 crashed on me after I disconnected from an ethernet network (but stayed connected via wifi). The backtrace suggests it's a bug in the plugin. I submitted it through ABRT to generate and collect all relevant data. More in downstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1296158

**Comment by majn** [comment]
It doesn't happen on every restart, right?

**Comment by Sesivany** [comment]
No, as far as I remember. ABRT also identifies it as the first crash of this kind on my machine.

**Comment by BenWiederhake** [comment]
Can you restart it with `pidgin -d > debug.log'`, and send it to us? This way, the debug log "survives" the crash. This gives more information about the crash, like what happened under the hood in which order.
The log may contain personal information, so you may not want to post it publicly.

**Comment by BenWiederhake** [comment]
The crash is due to a double-insertion in a tree.

I think this might have something to do with #173 (where a "broken" socket wasn't detected as such, and tgp continued to use a broken/closed connection). Just that in your case it tries to "restore" the names again, inserts them -- and then crashes, because the "old" names were never deleted.

But that's just a hunch. I just hope that it was fixed by the fix for #173. That fix is included in v1.2.5, so please do let us know if it happens again. And if you happen to have the log around the time of the crash, even better so :P

**Comment by Sesivany** [comment]
No, it doesn't occur any more, I think it's safe to say we can close this bug as fixed.
