### ISSUE TITLE
Groups chats do not appear

### ISSUE THREAD

**Issue by nazunalika** [majn/telegram-purple#255]
[pidgin.telegram.debug.txt](https://github.com/majn/telegram-purple/files/178840/pidgin.telegram.debug.txt)

This is my first time setting up the plugin with pidgin. I have used telegram just as a desktop app and on my phone, but I decided to use pidgin. However, the group chat I am in does not show up when I login. The debug log, from what I can tell, does not seem to hint to it. 

I'm not sure what the issue is. As a note, I did not create the group. I was invited to the group some time ago. I am able to talk to contacts that show up fine though. 

This occurs on both the Linux and Windows versions of pidgin and the telegram-purple plugin.

**Comment by BenWiederhake** [comment]
The group most definitely has been converted to a supergroup (200+ members).

We're working on it, but [supergroups aren't yet supported](https://github.com/majn/telegram-purple/issues/194) because they require a lot of extra code.

Closing as duplicate. Feel free to re-open if you doubt that the group is a supergroup.

**Comment by majn** [comment]
Here is how you use group chats in Pidgin:

https://developer.pidgin.im/wiki/Using%20Pidgin#HowdoIjoinanexistingchatroom
