### ISSUE TITLE
Newer windows builds?

### ISSUE THREAD

**Issue by TomTheDragon** [majn/telegram-purple#265]
Are there any plans for newer windows builds? The newest windows build is still at v1.2.4.
Would be really great to see some of the newer 1.3.x builds, because more and more groups i know get converted into super groups.

**Comment by BenWiederhake** [comment]
Since there currently *is no version 1.3.x* (it's still in development), there's also no Windows version yet.  We're well aware of the fact that supergroups and channels are out there.

However, 1.2.6 could/should be packaged for Windows, you're right. Currently, @EionRobb is the only one who knows how to do that. I'm trying to find a way to automate that step, but until then, we have to wait until he's got the time for it.

**Comment by TomTheDragon** [comment]
Hm.. i am not sure how hard it is to add something like this but.. how about adding cross-compiling so that everyone could then make own builds very easily?
I know it from the f-chat plugin (https://github.com/fcwill/fchat-pidgin) and its really simple to compile then.

**Comment by BenWiederhake** [comment]
Cross-compiling is made very difficult as some parts of tgl need to be executed *at compile-time*, so you either need to build on Windows -- or you have to copy `tgl/auto` (all the auto-generated source files, which amount to 10 megabytes, yuk!) from a non-cross build to the cross-compilation build.  Thus I kinda prefer non-cross builds.

**Comment by BenWiederhake** [comment]
As far as I can see, Eion Robb already uploaded the 1.2.6 builds.

**Comment by rodneyrod** [comment]
@BenWiederhake What about 1.3.0?
