### ISSUE TITLE
Missing dependency on Gentoo Linux, installation fails (xxd)

### ISSUE THREAD

**Issue by chaoscommander** [majn/telegram-purple#298]
The install script for Gentoo Linux (Portage) assumes that xxd is present on the system. However, if your favourite console editor is not vim, which is what provides xxd on Gentoo, it doesn't exist. So at the moment, as stupid as it sounds, a dependency on vim-core would be necessary to successfully install telegram-purple.

Error descr.: after the source is successfully compiled, the install step fails with "xxd: command not found".

**Comment by BenWiederhake** [comment]
xxd shouldn't be necessary, as it only creates the files `tgl/mime-types.c`, which should be part of the origtar.

Gentoo being Gentoo, I'll assume that some policy requires you to purge that auto-generated file.  If that really is the case (contact whoever maintains that package!), the packager will have to add that dependency, but only for the Gentoo package.  (Not the "build instructions" in telegram-purple's `README.md`.)

**Comment by pmiddend** [comment]
I'm observing this behavior with a -9999 package which pulls the source directly from git. Isn't it possible to replace xxd with something else? It sounds a bit silly to require vim to build your software.

**Comment by BenWiederhake** [comment]
"directly from git" → Again, the file you're talking about (`tgl/mime-types.c`) is already [part of the git repository](https://github.com/majn/tgl/blob/624cf5ac27433b9716c224ecaa8f1deee0616f99/mime-types.c).  So if it's missing after your checkout, then something went wrong on your end.

If the file isn't missing, but `make` still tries to recreate that file, then it's probably your filesystem that screwed up the timestamps.  In this (unfathomably unlikely, as `make` usually is able to get around these issues; also, if you use Arch then you probably don't use such an ancient filesystem) scenario, you might want to `touch tgl/mime-types.c` before `make`ing.

**Comment by BenWiederhake** [comment]
Tested in a clean chroot without xxd:

**Comment by pmiddend** [comment]
Well, I don't know how Gentoo handles all of the cloning, moving and unpacking stuff, but timestamps do seem to be "mixed up". mime-types.c has a later modification date and make thus tries to regenerate mime.types from it.

I still don't think it's wise to assume xxd is installed (and you are doing just that), but since you're being deliberate, I would close the issue. However, @chaoscommander is the one that opened it, so I can't. :D

**Comment by BenWiederhake** [comment]
> mime-types.c has a later modification date

That's perfectly okay since *the .c file is generated from the mime.types file*, not the other way around.

Still, I'm confused as to what was the actual problem.  Does it work for you now?

**Comment by pmiddend** [comment]
Whoops, sorry. I didn't look carefully enough, so I stopped the compilation and looked at the files that were checked out by the ebuild:

    stat mime-types.c
    File: 'mime-types.c'
    Size: 327218          Blocks: 640        IO Block: 4096   regular file
    Device: 803h/2051d      Inode: 3699050     Links: 1
    Access: (0644/-rw-r--r--)  Uid: (  250/ portage)   Gid: (  250/ portage)
    Access: 2016-08-22 23:05:48.921029504 +0200
    Modify: 2016-08-22 23:05:48.923029504 +0200
    Change: 2016-08-22 23:05:48.923029504 +0200

    stat mime.types
    File: 'mime.types'
    Size: 53051           Blocks: 104        IO Block: 4096   regular file
    Device: 803h/2051d      Inode: 3699052     Links: 1
    Access: (0644/-rw-r--r--)  Uid: (  250/ portage)   Gid: (  250/ portage)
    Access: 2016-08-22 23:05:48.923029504 +0200
    Modify: 2016-08-22 23:05:48.924029504 +0200
    Change: 2016-08-22 23:05:48.924029504 +0200

So the modification time stamp is mixed up, so make tries to regenerate mime-types.c from the mime.types file. Again, I don't know who's to blame here. I'll add the touch command to the ebuild which should, of course, fix the situation.

**Comment by BenWiederhake** [comment]
20ms distance in their timestamps?  Eion Robb suggested in dev chat that it's possibly due to the git checkout pulling the files in "the wrong order" … turns out he's right.

Ugh.  I want both of these points:
- make should re-create `mime-types.c` if it is outdated
- make should **not** re-create `mime-types.c` if it is "outdated" due to git working in some particular order

Hmm.  Many people use git and make simultaneously.  I don't think we're the first to stumble into that problem.

**Comment by chaoscommander** [comment]
Is the changed ebuild file already in the tree? I just tried eix-sync and smart-live-rebuild (using the -9999 package), but the install step still fails.

`>>> Install telegram-purple-9999 into /var/tmp/portage/x11-plugins/telegram-purple-9999/image/ category x11-plugins
make -j17 -l2 DESTDIR=/var/tmp/portage/x11-plugins/telegram-purple-9999/image/ install 
make -C tgl libs/libtgl.a
make[1]: Entering directory '/var/tmp/portage/x11-plugins/telegram-purple-9999/work/telegram-purple-9999/tgl'
xxd -i mime.types > mime-types.c
/bin/sh: xxd: command not found
Makefile:101: recipe for target 'mime-types.c' failed
make[1]: *** [mime-types.c] Error 127
make[1]: Leaving directory '/var/tmp/portage/x11-plugins/telegram-purple-9999/work/telegram-purple-9999/tgl'
Makefile:82: recipe for target 'submade' failed
make: *** [submade] Error 2
make: *** Waiting for unfinished jobs....`

**Comment by canaaerus** [comment]
It is indeed true, that git does not preserve modification times. Whenever you do a checkout, push, pull etc. the mtimes will be set to now. This is by design though, to prevent other problems, especially when checking out different branches. (See e.g. [this discussion](http://git.661346.n2.nabble.com/git-and-mtime-td1518843.html))

So if the only thing you are concerned about is deployment, you could of course use [order-only prerequesites](https://www.gnu.org/software/make/manual/make.html#Prerequisite-Types), which do not invoke a recreation of the target they change. Though usually for development this is not what you want. In that case Ben’s solution seems the most prudent: Warn if the build tool (xxd) is not available and use the existing file.

**Comment by Reedych** [comment]
Also you can simply install vim and all will work normally.

**Comment by chaoscommander** [comment]
> Also you can simply install vim and all will work normally.

Well yes, but if that's the desired solution, the package should depend on vim.

**Comment by chaoscommander** [comment]
Ah sorry, for some reason my attempt to rebuild some days ago failed, but now I see the problem has been fixed. Thank you!
