### ISSUE TITLE
http links do not show up in chat window of telegram-purple on Lx-Pidgin

### ISSUE THREAD

**Issue by Cbhihe** [majn/telegram-purple#314]
**Environment**:  Linux Ubuntu Desktop 14.04.5 
                         kernel 4.4.0-41-generic #61~14.04.1-Ubuntu
                         telegram-purple on Pidgin 2.10.9.
**Issue** 
1) Send or receive any http link with Telegram (Purple) on Pidgin.
Nothing shows on my screen/side of the IM chat session. 

2) Link only becomes visible only when I cursor-hover over it .

3) Chat session partners not on Lx/ubuntu/Pidgin but on the original Telegram app have no such trouble.

This is  long standing issue I have add for the past 60 days or so. It does not seem to be a fluke.

**Comment by BenWiederhake** [comment]
Huh, that sounds very weird.  Are you sure it's not due to some (mis)configuration of gtk themes and Pidgin?  For example, I know of a gtk theme that causes Firefox on my laptop to display "input field" text white on white.  Can you check that this isn't the case here, e.g. by changing the theme and restarting pidgin?

**Comment by Cbhihe** [comment]
Hi Ben, sorry for the belated reply. Have no clue as to why this happened. 
I migrated to a different box with a brand new Lx OS on it. I reinstalled everything from scratch and all works well and this issue should be closed. Cheers ! -cedric
