### ISSUE TITLE
RPC_CALL_FAIL 401: USER_DEACTIVATED

### ISSUE THREAD

**Issue by giuliosalis** [majn/telegram-purple#338]
Long time ago I deleted my telegram account. Now I create an account with the same number, but login give me this error.

**Comment by BenWiederhake** [comment]
Sound like you'll need either Telegram support to re-activate your account, or find a client that can do this.  I don't know any such client, but maybe https://web.telegram.org/ is worth a quick try.

I'll close this as "won't fix", since that would require a new dialog with the user and several untested (and possibly unimplemented, in tgl) RPC commands (which may or may not exist).  Feel free to re-open if you want to implement that.

**Comment by jsalatiel** [comment]
I am having this issue too. I can use telegram just fine in my android phone, android tablet, telegram web , but when i try telegram-purple i get RPC_CALL_FAIL 401: USER_DEACTIVATED.
Of course my account is not deactivated.

**Comment by giuliosalis** [comment]
I solved so: If you are on windows 1. Uninstall pidgin and the telegram plugin 2. Delete the hidden folder C:\user\[your user name]\AppData\Roaming\.purple 3. Install pidgin and telegram plugin. I'm no expert but I think this folder contain settings file and something rest in memory wich you deleted a telegram account.

**Comment by jsalatiel** [comment]
Thank you. I deleted the .purple/telegram-purple directory and it worked.
