### ISSUE TITLE
No way of seeing whether someone has read your message

### ISSUE THREAD

**Issue by dabeeeenster** [majn/telegram-purple#37]
This is part of the default telegram UI but is absent from Adium. Is it even possible in Adium? I've not seen a UI pattern for it...

**Comment by majn** [comment]
I don't think that this is even possible with Adium or Pidgin, I've not seen a single protocol plugin that displays read notifications of any sort. You could write a new message each time the message was read, but I think that this would be an disturbance during regular usage.

**Comment by shouya** [comment]
How about using a mark line that indicates the last read message? Just as what the Markline plugin looks like.

**Comment by JohnyDNU** [comment]
https://bitbucket.org/olegoandreev/purple-vk-plugin
Plugin for VK do this way.
It's very usefull. Especialy when your status is 'Away' ;-) Now in this status people will get my messages but their will looks like not readed. I think it's wrong.

**Comment by majn** [comment]
@JohnyDNU Thanks, this link was very helpful.

Apparently the Markline plugin solves this by editing the conversation HTML directly and surpassing any logging https://github.com/rosedu/Pidgin/blob/master/pidgin/plugins/markerline.c#L95 . This should work in theory, but there might be a few problems in our case:
- This appears to be highly implementation specific, I don't want to break support for telepathy-haze
- I cannot just append it to the end of the conversation like Markline does since this is about the messages the **other** user has read. If a conversation is opened I would need to find the last message with a read notification and insert it into the middle of the text buffer.

All of this is seems really hacky to me, so I'm going to postpone this issue until other more urgent issues are solved. I am still missing a lot of Telegram features that are well-supported by Libpurple.

**Comment by majn** [comment]
I've added an opt-in setting that will display read notifications as system messages, kind of like Telegram-CLI does. But be aware, it can be really annoying.

I decided to not implement the solution of the markerline plugin, since this would be Pidgin-dependent code and break compatibility with other Libpurple clients.
