### ISSUE TITLE
Nothing happens after adding account to pidgin

### ISSUE THREAD

**Issue by 6vasia** [majn/telegram-purple#409]
And sometimes it crashes.

I have compiled from source (af200e0), did global install (make install). Then started pidgin and added new account. 

First time it asked for first name and last name, I've recieved a code in sms, and that's it. 
I've deleted account, re-added, and now I dont get anything at all.

prpl-telegram: tgl requests user input, tgl_value_type: 0, prompt: phone number:, count: 1
prpl-telegram: ping alarm
prpl-telegram: ping alarm
...
full log: https://pastebin.com/DxZbABKX

**Comment by BenWiederhake** [comment]
You are running the newest version.  Good!

You apparently use x86, i.e., 32-bit hardware.  This means that tgp is going to be slow, *especially* the first login (factorization, discovery, log fetching).  It may even look like crashing/hanging, because tgp tries to crunch a lot of information.

    (19:02:50) prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account
    (19:03:02) prpl-telegram: tgl requests user input, tgl_value_type: 0, prompt: phone number:, count: 1
    (19:03:45) prpl-telegram: tgprpl_close()

### If you entered the SMS code and then it just hung

Well, 55 seconds is a bit short.  (Before you complain: I know, I know, 55 seconds *should* be enough, but tgp and tgl are slow, and have to do a lot, because of the libpurple API.)

Maybe it helps to remove your account in pidgin, shut down pidgin (not just close the window), delete the account directory (`~/.purple/telegram-purple/+7966xxxxxxx`), and try again.  Please have patience, the first bootup takes rather long.  On my slow laptop the first startup took around 3 minutes, so if you're active in a lot of channels/groups/supergroups, it might take quite a while.

**Comment by 6vasia** [comment]
Well, now it keeps saying "Please enter the login code that you have received via SMS.". Where do I enter the code? (telegram-cli now works either)

**Comment by 6vasia** [comment]
BTW, I was getting "Too many attempts..." in official client, I guess tgl does not handle this.

**Comment by 6vasia** [comment]
At least it works with spectrum.

**Comment by 6vasia** [comment]
Seems to work now with pidgin.

**Comment by BenWiederhake** [comment]
Thanks for the follow-up!
