### ISSUE TITLE
Secret chats entity-escape any of '<' , '>' , ' " ' and '&'

### ISSUE THREAD

**Issue by loungecube** [majn/telegram-purple#430]
When writing messages in a secret chat, any characters from the set { < > & " } are replaced with the corresponding sequence from the set { &lt; &gt; &amp; &quot; } in the printed text on all pidgin client in the chat.

**Comment by criztovyl** [comment]
I think you mean `< > & "` are replaced with `&gt; &lt; &amp; &quot;`?

(Most likely you wrote that, but note that text in GitHub issues is Markdown where you can aslo include any valid HTML so your entites are expanded in the resulting text :) )

**Comment by loungecube** [comment]
Aaah crap. You are right.

**Comment by majn** [comment]
Confirmed, this is an issue with libtgl not using HTML markup for encoding in secret chats.

Basically 
- non-encrypted chats require HTML to be escaped (otherwise they will crash once parsing unknown symbols) and will unescape it for you

- encrypted chats do not parse HTML and won't unescape it for you

**Comment by majn** [comment]
https://github.com/majn/telegram-purple/commit/38dd27e0f349a27c010d8999d50a891a268ed665
