### ISSUE TITLE
PPA build always fails with No git available. Can't reconstruct commit.h (dev 1.4.0)

### ISSUE THREAD

**Issue by khurshid-alam** [majn/telegram-purple#455]
I am trying to build in a ppa from dev-1.4.0. But it always fails with 

`No git available. Can't reconstruct commit.h`

This what I have done

```
git clone -b dev-1.4.0 https://github.com/majn/telegram-purple
cd telegram-pulple
git clone -b dev-1.4.0 --depth=1 https://github.com/majn/tgl.git
git remote add launchpad lp:~khurshid-alam/telegram-purple/+git/packaging
git push launchpad master
```

But when I start compiling from that branch it gives the same error. I locally executed commit.h.gen which creates commit.h. Then push it.But it still fails with the same error.

Any idea?

@BenWiederhake

**Comment by BenWiederhake** [comment]
Hmm.

Your sequence of commands does not actually contain any build command.  Which machine actually does the building?  The thing is: either `.git` or `commit.h` must be available when the actual build process starts.  In other words: Either give full instructions on how to build to the build machine, or build a "origtar", by invoking `./gen-origtar`.

Also, regarding `git clone -b dev-1.4.0 --depth=1 https://github.com/majn/tgl.git`:
That's not how submodules work.  It doesn't cause any of your current problems, but nothing good can come out of it.  Try any of the following:
- Use `--recursive` as specified in the [README](https://github.com/majn/telegram-purple#1-clone)
- If you really desperately need to save bandwidth and know what you're doing (i.e., don't intend to use anything of the history, which for example is violated when you invoke `./gen-origtar`), then use `--depth=1` on the "outer" repository instead.  That's the much bigger one (15 MiB in contrast to only 1.4 MiB).
- If you really desperately want to do it step-by-step (i.e., because you cannot change much of the initial clone), then invoke `git submodule update` [like this](https://travis-ci.org/BenWiederhake/telegram-purple/jobs/396189267#L438) to download the tgl repo.

**Comment by khurshid-alam** [comment]
@BenWiederhake

I don't need build command because I am not running it locally. I am pushing to launchpad and launchpad  ppa is running the build. Anyway I fixed the build by running commit.h.gen locally and then removing it from .gitignore. 

Launchpad Recipe: https://code.launchpad.net/~khurshid-alam/+recipe/telegram-purple-daily-1
Source repo: https://code.launchpad.net/~khurshid-alam/telegram-purple/+git/packaging

But at the moment the workflow is github-> local machine-> laumchpad. However what I want is a daily build ppa directly from github. Github-> launchpad ppa. Launchpad support git to git import. This is the recipe in which I tried to the same.

https://code.launchpad.net/~khurshid-alam/+recipe/telegram-purple-daily

But the problem is if commit.h does not exist it exists with `exit 1`. And build stops. 
```sh
if ! (command -v git && git status) >/dev/null 2>&1
then
  if test -r commit.h
  then
    echo "No git available. Assuming everything is up-to-date."
    exit 0
  else
    echo >&2 "No git available. Can't reconstruct commit.h"
    exit 1
  fi
fi
```


One solution is to remove commit.h from gitignore and modify the gen sctipt so that it overwrites commit.h regardless the previous contents.

**Comment by BenWiederhake** [comment]
> launchpad ppa is running the build

And to do so, it necessarily uses some kind of script, and necessarily access the git repo.  Why don't you use either?

> what I want is a daily build

We don't update that often.  By far.

> But the problem is if commit.h does not exist it exists with exit 1. And build stops.

Great!  So it works exactly as intended.

> does not conform to debian packaging properly

Do you mean your own modifications?  Well, congrats then.

Do you mean our setup?  Because that doesn't make sense.  The debian packaging stuff is in `debian/`, where it belongs.  `Makefile` does the actual building.

All in all, I don't really understand what you want.

Do you just want to clones and build it?  Great, then `git clone` and `make`, WITHOUT throwing away the git repo in between.

**Comment by khurshid-alam** [comment]
> And to do so, it necessarily uses some kind of script, and necessarily access the git repo. Why don't you use either?

I imported the git repo from github to launch. To launchpad it's just a local git repo on their machine. They are downloading all the dependencies and compiling like travis cl.

Launchpad ppa build is developed in such way that it can compile any binary from source without any sort of interaction from user provided a proper debian folder exists. https://help.launchpad.net/Packaging/SourceBuilds/Recipes 

If user needs to run a script before that then simply modify /debian/rules 

```make
override_dh_auto_configure:
    echo "" > commit.h
    dh_auto_configure
```

> We don't update that often. By far.

It only compiles when it detects a change in source.


> Great! So it works exactly as intended.

Ah No. Make should never throw exit 1 like that.

> Do you mean our setup? Because that doesn't make sense. The debian packaging stuff is in debian/, where it belongs. Makefile does the actual building

Yes your setup.

Source packages are being compiled in space called repository in debian. And with current setup any  build will fail. You can confirm with any debian travis build. 

> Great, then git clone and make, WITHOUT throwing away the git repo in between.

Lets assume there is no git (but git is installed). Entire repo is available to you locally. And then if you run dhbuild (which eventually runs make) it will fail.
-----

**Solution:**
From #242 

```
commit.h must change whenever it disagrees with the current git commit
commit.h must not change whenever it agrees with the current git commit

commit.h is a regular file which depends on a .PHONY target commit. Building commit.h only touches commit.h if necessary. (=> 1 & 2)
```

How about we simply provide a empty commit.h and overwrites with a required git commit regardless whether it agrees with git commit or not so we don't need that check. It solves all the problems.

Or

If you must need the script that way then simply provide a commit.h through debian/rules which will simply create a empty commit.h before running commit.h.gen.

**Comment by BenWiederhake** [comment]
> I imported the git repo from github to launch. To launchpad it's just a local git repo on their machine.

Great!  So everything would actually be fine if you don't throw anything away.

> They are downloading all the dependencies and compiling like travis cl. There no .git directory inside PKGBUILDDIR. And so git status fails.

So you throw away something and then complain that it's missing.  Not the project's fault.  Literally clone, configure, and make.  Building can't be simplified much further.

> Launchpad ppa build is developed in such way that it can compile any binary from source without any sort of interaction from user provided a proper debian folder exists.

And we guarantee that you can do that from any origtar as provided with each release (see [Releases page](https://github.com/majn/telegram-purple/releases)), or after a fresh git clone.  If you clone and then throw away something (i.e. `.git/`), it's incomplete.

This is like complaining that a program doesn't compile after you delete some of the C source file.

> `echo "" > commit.h`

This is a horrible idea on so many levels.  This would lose all the versioning information there is, and finding out which version is a significant part of debugging.  (Admittedly, we barely ever fix anything, but the version is really important.)

The "script" the user needs to run should instead be:

    test -d .git || test -f commit.h || { echo "Why did you delete files?!  It's not gonna compile now."; exit 1; }

> Ah No. Make should never throw exit 1 like that.

It doesn't.  It exits with code 2, just like the man page describes it.

    $ make commit.h
    No git available. Can't reconstruct commit.h
    Makefile:130: recipe for target 'commit.h' failed
    make: *** [commit.h] Error 1
    $ echo $?
    2

> Source packages are being compiled in space called repository in debian. And with current setup any build will fail. You can confirm with any debian travis build.

So [green means failing](https://travis-ci.org/majn/telegram-purple/).  Good to know.

The reason why it doesn't fail in Travis:  It doesn't randomly decide to delete a bunch of files.

The reason why it would work perfectly well in Debian: Because there we would only publish releases, and releases have a user-friendly [origtar](https://github.com/majn/telegram-purple/releases) available, so that no git is needed.

> Lets assume there is no git (but git is installed). Entire repo is available to you locally. And then if you run dhbuild (which eventually runs make) it will fail.

If you don't have git available while working with a package that is hosted on git, maybe the term "user" is more appropriate.  In that case, stick to the releases.  Or use git to look at the developer version, if you can tolerate incomplete translations, if you really wanna stay up to speed.

> How about we simply provide a empty commit.h and overwrites with a required git commit regardless whether it agrees with git commit or not so we don't need that check. It solves all the problems.

Except that you created two new problems which go *against* everything.  One is above, the versioning stuff.  The other defeats how make works, because you just destroyed incremental builds.

---

I'm sorry, but I don't think we will converge on this in any meaningful way.  Good luck and thanks for the suggestions!  But no thanks, I don't want to implement those suggestions, and if the only reason that it's broken is just that you deleted some files, then this is not telegram-purple's issue.

**Comment by khurshid-alam** [comment]
@BenWiederhake 

I think you misunderstood. **I did not delete any file.** . I upload to loaded as it is. But launchpad doesn't copy `.git` to build dir because it runs dhbuild which automatically creates orig.tar.

I understood the versioning and incremental part. But I still feel it should be done from /debiam/rules rather than executing git command from makefile.

>The reason why it would work perfectly well in Debian: Because there we would only publish releases, and releases have a user-friendly origtar available, so that no git is needed.

In  that orig.tar commit.h is already present but has same makefile which has same git command and the command fails as there is no `.git` in orig.tar.  So how does it make any difference?

Is there any RFP bug filed in debian? Because I want to see their packaging. How  they do it? May be I can use that.

**Comment by BenWiederhake** [comment]
> it runs dhbuild which automatically creates orig.tar.

Trying to generate the origtar automatically seems like asking for trouble.  It appears that historically, `make dist` is supposed to do that, but for that step it needs the `.git` folder because that's the only place that can possibly know the current commit hash.  Does dhbuild call `make dist`?  If so, why is `.git/` already unavailable at that point?

So either tell launchpad to create the origtar using `make dist` in the original git clone, or find another way to provide the actual origtar.

> I understood the versioning and incremental part. But I still feel it should be done from /debiam/rules rather than executing git command from makefile.

But ultimately, where do you think we could store the information what hash the current commit is?  In a file?  But then we would need to update that with every commit (kinda unreliable), and also need to know the commit hash in advance (to write it into the file which is then part of the commit).  So the only place for this piece of information in any "non-static view" of the project (i.e., git clone) is in the git folder itself.  Reading it via git tools is then easy.  In a "static view" (i.e., origtar), it can be just easily generated as part of that process.  That's why we cannot create that file in the git repo.  Because it's not a meaningful thing to ask for.

> In that orig.tar commit.h is already present but has same makefile which has same git command and the command fails as there is no .git in orig.tar. So how does it make any difference?

Because it handles that case like it should: It notices that `commit.h` exists and `.git/` does not exist, and then decides to accept `commit.h` as it is.

… shit.  That's what it *should* do.  It doesn't.  Thanks for reporting.

**This is a bug.**

> Is there any RFP bug filed in debian? Because I want to see their packaging. How they do it? May be I can use that.

I think you meant [RFS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835141), but an even more boring [RFP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=833793) exists, of course, too.  I have good reasons to [abandon that effort](https://github.com/majn/telegram-purple/pull/408#issuecomment-390685368).

**Comment by BenWiederhake** [comment]
No, wait, sorry, I was making a mistake while trying to reproduce it.  With commit.h in place the following happens:

    $ ./commit.h.gen 
    No git available. Assuming everything is up-to-date.
    $ echo $?
    0

So build succeeds.  So no bug.  Can you verify that?

**Comment by BenWiederhake** [comment]
I take that as a "Yes, I've been using `./gen-origtar` wrong".

**Comment by khurshid-alam** [comment]
Consider following scenarios

A) No .git, commit.h present
```
$ ./commit.h.gen 
No git available. Assuming everything is up-to-date.
```

which is fine. But it doesn't remove commit.h.gen from makefile.in. So debuild will again execute it even though commit.h  was already created in orig.tar by running same command.

Even if user forgets to run ./commit.h.gen it will still compile.



B) No .git, commit.h is not present

```
$ ./commit.h.gen 
No git available. Can't reconstruct commit.h
echo $?
1
```
In this case user has to run ./commit.h.gen before running make or debuild. Otherwise it won't work. Usually that extra manual step shouldn't be necessary.

C) .git present

I this situation it doesn't matter whether commit.h is present or not. It won't go into that loop. It will simply create or overwrite commit.h. Build works without any user intervention.

So makefile is being used for all these situation. Only for situation B, it fails. 

We overwrite commit.h in C). My question is why can't we do the same for B) ?

**Comment by BenWiederhake** [comment]
> **A) No .git, commit.h present**
> But it doesn't remove commit.h.gen from makefile.in.

I don't know what you mean here.  `Makefile.in` should never be automatically modified.  The corresponding rule in `Makefile` should not vanish, because, well, why should it.

> So debuild will again execute it even though commit.h was already created in orig.tar by running same command.

So what's the problem?  debuild runs the Makefile, which runs `commit.h.gen`, which leaves everything as-is, and everyone is happy.

> Even if user forgets to run ./commit.h.gen it will still compile.

In this scenario there already is a `commit.h`, so it doesn't need to be recreated.  Also, the Makefile calls `./commit.h.gen`, so the user isn't supposed to call it in the first place.  And there is no git anyway, so where would it even get the information from?  I do not understand what your problem is.

> **B) No .git, commit.h is not present**
> In this case user has to run ./commit.h.gen before running make or debuild. Otherwise it won't work. Usually that extra manual step shouldn't be necessary.

No, in this case the user is a moron for deleting crucial files and still expecting it to work.  I've stated this several times now.

> **C) .git present**
> In this situation it doesn't matter whether commit.h is present or not. It won't go into that loop. It will simply create or overwrite commit.h. Build works without any user intervention.

What "loop"?  Also yes, congrats, you discovered that `commit.h` is a build artifact, as I've been trying to tell you for quite a while now.

> So same makefile is being used for all these situations. Only for situation B, it fails.

Look.  You might have a factory that generates car engines (let's call this factory `.git/`), or you might have a single car engine (let's call this `commit.h`).  Scenario B is when you go into your car, have no car engine, have no means to create a car engine, and then write an issue about "car is broken plz fix".  No!  Why did you remove the engine if you want it to run?!  Why do you delete files if you want it to compile?!

> We can overwrite commit.h in C). My question is why can't we do the same for B)?

Because you ripped the heart out of a puppy and are now angry that it doesn't want to be your friend anymore.

> Can we not modify the script slightly so that it works even for B) without user intervention?

The fact that you really ask this question show that you never read anything that I wrote.

Locked, because you can't read.
