### ISSUE TITLE
Pndgin creshes at start

### ISSUE THREAD

**Issue by Loki3000** [majn/telegram-purple#463]
Installed telegram purple version 1.3.1-1\~webupd8~bionic0 from ppa repository.
pidgin crashes after activate telegram account:
```
(22:25:00) prpl-telegram: outbound rpc connection from dc #2 becomed ready
(22:25:00) prpl-telegram: Sent query #6595968108599078912 of size 120 to DC 2
(22:25:00) prpl-telegram: adjusting CLOCK_MONOTONIC delta to 0,298914
(22:25:00) prpl-telegram: work_new_session_created: msg_id = 6595968109186477057, dc = 2
(22:25:00) prpl-telegram: regen query from old session 22236940154140
(22:25:00) prpl-telegram: regen query from old session 22236117659436
(22:25:00) prpl-telegram: Alarm query 22236940154140 (type 'get config')
(22:25:00) prpl-telegram: Resent query #22236940154140 as #6595968108599078916 of size 120 to DC 2
(22:25:00) prpl-telegram: error for query 'get config' #6595968108599078912: #400 AUTH_KEY_DUPLICATED
pidgin: mtproto-client.c:1207: mpc_on_get_config: Проверочное утверждение «success» не выполнено.
```

**Comment by BenWiederhake** [comment]
It seems like you copied the configuration folder (with the files `auth` and `state`) to a different machine, and use it in both places at the same time.  In that case, delete the broken copy and login from scratch.
Either way, go to the web interface (web.telegram.org) and remove any sessions which you think should not be running anymore.  Don't worry, if you accidentally close something which is still being used, you only have to log in again on that client.

Finally, note that we do not support webupd8 because they don't really stay in any contact and it seems to be difficult to reach them.  Closing as unsupported.  Feel free to reopen if this still occurs with dev-1.4.0.

**Comment by Loki3000** [comment]
Thanks! Now it works.

**Comment by AcostArichA** [comment]
Thank You! And for me it  turned out to be useful  too!!!
