### ISSUE TITLE
make local_install fails when ~/.purple/plugins doesn't exist

### ISSUE THREAD

**Issue by p-p-q** [majn/telegram-purple#47]
Title says it all. Maybe check if the plugins/ dir (or better, the full path) exists in the Makefile?

**Comment by BenWiederhake** [comment]
(Moved my comment from #!100 to here -- sorry for the confusion. Originally posted on: 2015-10-09)

Uhh ... this is a deeper problem. `make local_install` is very broken: See #100  telegram-purple expects the public key in a folder where only root can write (`/etc` has permissions `drwxr-xr-x root root`). It would take little but non-trivial effort to make `local_install` work.

However, it looks like nobody ever needed it, so I'm in favor of dropping that feature completely.

**Comment by BenWiederhake** [comment]
Just to reiterate:

If you would like to see a feature like this again, please open a new
bug and just reference this issue #47. A few words about your scenario would help, so we can find a good alternative place for `server.tglpub` and how to check for it.

**Comment by p-p-q** [comment]
That's fine by me, thanks. It would be nice to be able to set up a chat program without root access to a machine, though. Also, what is the reason for making the server pubkey read-only for normal users? I don't see any security gains, but then again, I don't really know how Telegram or telegram-purple works.

**Comment by BenWiederhake** [comment]
Do you really have that use-case? Is there a machine where you don't have root access, but want to store your Telegram login data? If so, please come to the group chat (see README.md) so we can find a good solution.

To your second point: The server pubkey really should be read-only. I'd even hardcode it directly into telegram-purple (even vysheng did it in tgl!), since the pubkey is the only verification you have that you're talking with a telegram server. So nobody should need to change it.

**Comment by p-p-q** [comment]
No, I just meant that, as a matter of principle, userland-only programs should not need root access to set them up to work properly. At least, that's one way of looking at things. But, personally, I don't really depend on the local_install feature.
IMHO, hardcoding it makes way more sense than giving it to root as 644, yea.
BTW, thank you for working on this!

**Comment by BenWiederhake** [comment]
Sure, and as you can see from the reference, I just found such a use-case. So yeah, I'm working on that. (But translations and protocol icons won't work, because those are expected to be in a folder where only root has access.)

You said "hardcoding [the pubkey] makes way more sense".
Huh? Why? Although it'll take at least one or two decades, the pubkey **will** change, earlier or later. Being able to change the pubkey without changing the binary is kinda nifty. (Note that this does NOT increase security/safety of anything.)

**Comment by BenWiederhake** [comment]
Oh, and regarding the local installation thing: Go on and implement a `apt-get local-install <packagename>` command. Many people want that :D

**Comment by p-p-q** [comment]
Yeah that would be nice :) But apt-get source, ./configure and make usually leave you with a working executable, no need to install.. 
I know that hardcoding is not a security gain. If a stranger has local access to your machine and can change the key (no matter if in a file or in the source), Telegram is the least of your worries.
But since the user is discouraged to change the key anyway, it makes sense to me to hardcore it, for now. Putting it in a file would be useful if there was a key update mechanism in the client, which I gather there is not(?). So, since you have to update the client anyway to get a new key, it might as well go into the source. A user-owned, updatable key file would be even better but if I got you right, that's not an optionat this point..?

**Comment by BenWiederhake** [comment]
I [just implemented it](https://github.com/BenWiederhake/telegram-purple/commit/421d251bc3917529388af7edd52e3a644f992bc8). (Sorry for not referencing it). The commit after it (as seen from my branch 'beta4') handles the corresponding make targets. So ... I guess this can be marked as "closed" once it gets merged.

**Comment by p-p-q** [comment]
Cool, thanks.
