### ISSUE TITLE
Sent message from other device starts a new conversation in Pidgin

### ISSUE THREAD

**Issue by felagund** [majn/telegram-purple#476]
I am not sure if this is a bug in Piding or telegram-purple.

What happens:
1 I sent a messge from web interface.
2 a Pidgin window opens with the message

What should happen:
No such window should open (but I would still like sent messages to be displayed in an already opened window if I am using multuple devices to reply in a conversation).

Facebook-purple has a setting for this, but then it fails to show sent messages from other devices altogether (still,such a setting would be improvement as well).

**Comment by BenWiederhake** [comment]
The window opening is unavoidable; that is, if you want the message to show up at all.  There's no way to tell pidgin "We received this message, but don't open a new window for it, it's fine."

I recommend opening conversations in *tabs*, which can be selected in the settings somewhere, and just leaving it open indefinitely.  This way it doesn't bother me, and hopefully doesn't bother you either.

You're welcome to implement the same switch as facebook-purple has, and make a PR.  And while you're at it, I strongly recommend looking into how we could replace tgl with libtd.

**Comment by felagund** [comment]
So here: https://developer.pidgin.im/ticket/17364#ticket

**Comment by BenWiederhake** [comment]
Eion's answer (hey Eion!) indicates that tgp should be able to check whether the conversation is currently open or not.  I … wasn't aware that this is even possible, and can't imagine that this even makes sense.  After all, if we now open the conversation (e.g. because someone else responded), the own messages should appear.  Is the prpl responsible for keeping track of it?  Or is there a specialized call for "append this to the log, but don't open the conversation window"?  If so, why is there a need to check whether the conversation is open?  I'm thoroughly confused.

*I* am not able to implement this.  That's all I can say.  As always, a PR is very welcome.

**Comment by felagund** [comment]
Not sure about the technical stuff, but for me, the logic would be "do not open the window but log the message, and when the other party responds, display the message from log as is set by Pidgin preferences".
