### ISSUE TITLE
How-to hide my Hostname OS, IP-address from Active Session info

### ISSUE THREAD

**Issue by DJxZeonExpert** [majn/telegram-purple#483]
Hi guys, Ben!
How-to hide my Hostname OS, IP-address from Active Session info. When I looking for anonymizing in Telegram-purple, i not finding this Open option for hide my hostname/OS from Active Info. Can You help me finding this function/struct in your source code?

**Comment by BenWiederhake** [comment]
The options are not there because it doesn't make sense.

"Hostname OS": Bullshit.

Hostname: Is not transmitted.

OS name and version: Go to line `tgl/queries.c` line 1827, and change the 1 to 0.  That suppresses most info, and shouldn't break anything.
If that doesn't suffice for you, go to line 522, and replace the constants there with more boring stuff.  I strongly recommend leaving the `TLS->app_version, TGL_VERSION` part in place, as Telegram probably has some compatibility stuff to work around tgl quirks.  This may break things anyway.

IP-address: Bullshit.

If that doesn't answer your question, feel free to write again.  But we probably won't do anything more than what already exists.

**Comment by DJxZeonExpert** [comment]
Ben, sorry for notification this mail, for i just abouted too more hours worked around in was sources, i know what this <allow_send_linux_version>, but not quiet sure for this, anyway thank for you request/answer!


>Воскресенье, 17 февраля 2019, 13:17 UTC от Ben Wiederhake <notifications@github.com>:
>
>The options are not there because it doesn't make sense.
>"Hostname OS": Bullshit.
>Hostname: Is not transmitted.
>OS name and version: Go to line tgl/queries.c line 1827, and change the 1 to 0.  That suppresses most info, and shouldn't break anything.
>If that doesn't suffice for you, go to line 522, and replace the constants there with more boring stuff.  I strongly recommend leaving the TLS->app_version, TGL_VERSION part in place, as Telegram probably has some compatibility stuff to work around tgl quirks.  This may break things anyway.
>IP-address: Bullshit.
>If that doesn't answer your question, feel free to write again.  But we probably won't do anything more than what already exists.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Белоусов Феликс
