### ISSUE TITLE
Windows binary builds are missing

### ISSUE THREAD

**Issue by Neustradamus** [majn/telegram-purple#484]
@majn: Can you add Windows binary files for all versions?

**Comment by BenWiederhake** [comment]
You can find the current *development-grade* Windows installer [here](https://github.com/majn/telegram-purple/pull/446#issuecomment-381402503) and [here](https://github.com/majn/telegram-purple/pull/446#issuecomment-466580622) (same thread).

All builds before 1.4.0 were done my Eion Robb, and can be found on his website.  Note that they are pretty much outdated and unusable by now, which is why we won't upload them here.  (Big thanks to Eion for making them, back in the days!)

1.4.0 is still not released, so we can't attach these builds to a release yet.

**Comment by Neustradamus** [comment]
@BenWiederhake: Thanks for your answer, it is not possible to add @EionRobb builds directly with tags?
And add new in https://github.com/majn/telegram-purple/releases too?
It is better for users...

**Comment by BenWiederhake** [comment]
I already answered these questions.  Here they are again.

All builds before 1.4.0 were done by Eion Robb.  Before that.  Newer builds will not be done by him.
His builds are pretty much outdated and unusable by now, which is why we won't upload them here.  This includes the upload method "tag" and "release".

And yes, we intend to put them on the release page.  We haven't, because there aren't any such releases yet.
