### ISSUE TITLE
Wrong encoding in Spanish (es) localization

### ISSUE THREAD

**Issue by bidaian** [majn/telegram-purple#493]
As you can see below, there seems to be a problem with the utf-8 encoding of es.po

![ekrankopio](https://user-images.githubusercontent.com/378695/57591757-543dc300-7509-11e9-8a37-2510a6d59781.png)

**Comment by BenWiederhake** [comment]
Looking at "autenticaciÃ³n" (a-tilda power-of-three) specifically, it
seems the following happens:

- The file es.po correctly contains the UTF-8 sequence 0xC3 0x83 (for ó,
o with rising accent)
- For some reason, your pidgin installation tries to interpret it as
Windows-1252 instead of UTF-8, as suggested by this helpful tool:
https://www.i18nqa.com/debug/utf8-debug.html

Try convincing Pidgin to use UTF-8.

If that really, really doesn't work, I will have a look at how to make a
Windows build where all .po files are mangled beforehand.  But this
would be a last resort, not my first action.

(I sent this earlier in a direct mail to him, but it's supposed to be a public response.  Whoops.)

**Comment by bidaian** [comment]
@BenWiederhake, the problem is in the es.po file, it has mixed iso-8859-1 and utf-8 encodings. If I choose es_AR (basically the same translations) you can see how they show up alright.

![ekrankopio](https://user-images.githubusercontent.com/378695/57721882-cbdc3100-7674-11e9-9eaa-06719412f94e.png)

For example, you can see that mix in [this line](https://github.com/majn/telegram-purple/blob/9ba0e5702d0c17f93e7830bc35cba331f90583ba/po/es.po#L232) - wrong - and [this line](https://github.com/majn/telegram-purple/blob/9ba0e5702d0c17f93e7830bc35cba331f90583ba/po/es.po#L204) - right -.

**Comment by BenWiederhake** [comment]
Awesome, thanks for the analysis!

I'm sorry, but I can't pull this. :(
Our translations are hosted on Transifex, please edit them on the [resource page](https://www.transifex.com/telegram-purple-developers/telegram-purple/dev-strings-v142/).  You will need to make an account and apply for the [Spanish Translation Team](https://www.transifex.com/telegram-purple-developers/telegram-purple/language/es/), but all this should be just a few clicks.

I'll add you to the team as soon as I come around to it.

**Comment by BenWiederhake** [comment]
Also, if you have a suggestion where we could advertise transifex more prominently, I'd gladly sprinkle the link all over the repo.

**Comment by bidaian** [comment]
Ok. It's done in transifex in the resource page you linked (I uploaded the po file). About advertising transifex, maybe a mention the the README would help.

**Comment by BenWiederhake** [comment]
I pulled the translations and put them in 1.4.2.  If you haven't already, you can pull and install it, this should resolve all encoding issues then.  Thanks again for sharing :)

**Comment by bidaian** [comment]
Yes, pulling the translations solved the issue. Thanks.
