### ISSUE TITLE
Failed to find Pidgin installation

### ISSUE THREAD

**Issue by br4nnigan** [majn/telegram-purple#507]
windows installer fails to find pidgin installation and aborts

OS: Windows 7

Installer: https://github.com/majn/telegram-purple/releases/download/v1.4.1/telegram-purple-1.4.1+gd3d090917d.exe

not sure why, or why I can't point to the directory manually

**Comment by BenWiederhake** [comment]
What exactly is the error message?  Does it say `Failed to find Pidgin installation. Please install Pidgin first.`?  If so, the installer failed to find the registry keys, which should have been created when installing pidgin.  Have you installed pidgin in any unusual way?  I want to figure out what happened.

**Comment by cyorps** [comment]
Same issue here!

OS: Windows 10 - 1903 -Build 18362.145

At first AV-Engine (F-Secure) blocked this install process like described in hints. After I was whitelisting it at AV-Engine, I get the same error without blocking from F-Secure. In eventlogs I can't find any hint about problems. During install there is nothing new in %windir%/temp and in %appdata%/local/temp exists a folder with 3 files (InstallOptions.dll | ioSpecial.ini | modern-wizard.bmp) without a protocol file.

**Comment by br4nnigan** [comment]
@BenWiederhake the whole error message I get is "Failed to find Pidgin installation" 

I realize I am on an outdated version of Pidgin (2.12) for reasons so I guess that disqualifies me from support here.

I don't remember how I installed Pidgin, I guess the standard way? It shows up in my windows list of installed programs.

**Comment by BenWiederhake** [comment]
@cyorps: Those filenames don't ring a bell.  I don't think they are related to telegram-purple.

@br4nnigan: Alright, then the hard way.  In your Registry, please look at "HKLM\Software\pidgin" and "HKCU\Software\pidgin".  The installer expects at least one of them to be a path that contains the file "pidgin.exe".  Otherwise, it shows the error you described.

- Do your registry keys exist?
- If not, do you have a guess why they weren't generated by the Pidgin installer?  Can you generate those registry keys by hand?
- If yes, does the "pidgin.exe" exist?  If so, wtf?  If not, why does it point to the wrong directory?

**Comment by br4nnigan** [comment]
@BenWiederhake 
That's it.

I only have a pidgin key down the current user directory, not in local machine.

I use Windows on a non admin account. When programs need admin during installation they prompt the admin password via UAC. I think pidgin did not do this because when I run regedit as admin (which I must to change values) then the key is also missing in the current user software directory.

The telegram-purple installer runs in admin mode.

Adding the key to the admins CU directory fixes the error.

Thanks for investigating!

**Comment by BenWiederhake** [comment]
I'm going to assume that manually setting the registry keys works for both of you.  If anyone is interested in fixing this permanently, please see here: https://github.com/majn/telegram-purple/issues/508
Or just submit a PR.  Thanks!
