### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by Megachip** [majn/telegram-purple#52]
Is it possible to build telegram-purple on/for windows?

**Comment by majn** [comment]
Unfortunately, at the moment no. 

I've started trying to cross-compile it with MinGW for Windows, but as it turns out, the library libtgl doesn't seem to compile with MinGW either, so I would have to fix that first and the author would have to merge my changes. I'm probably going into that once I've got more time.

**Comment by intika** [comment]
thanks would be nice :+1 :)

**Comment by chpii** [comment]
You can try to make it with [MSYS2](http://sourceforge.net/projects/msys2/), https://msys2.github.io/

Sample PKGBUILDs are already in [AUR](https://aur.archlinux.org/packages/?K=telegram-purple)

You can read about it on their [Wiki](http://sourceforge.net/p/msys2/wiki/Home/) and ask on #msys2 at irc.oftc.net

**Comment by Croydon** [comment]
Windows support would be awesome!

**Comment by ZetCoby** [comment]
We really need this for windows too T_T

**Comment by majn** [comment]
FIY, here is the list of things left to do for the Windows port:

- libpurple needs to compile with MinGW
- libtgl needs to compile with MinGW, see  (there are missing randomizer functions that need to be replaced and the build process might need to be adapted for MinGW)
- Port libtgl from openssl to libgcrypt. For Windows I definitely need to provide the binaries as the compile process would be too much effort, but because of some GPL licensing issue I'm not allowed to redistribute the binaries for Windows until I find a way to drop OpenSSL.

**Comment by Croydon** [comment]
The OpenSSL license is changing: https://www.openssl.org/blog/blog/2015/08/01/cla/
Not sure if this is helping.

**Comment by willrea** [comment]
@Croydon APL v2 is only compatible for being included in GPLv3 projects only. Since libtgl is GPLv2 we're still in the same situation.

**Comment by majn** [comment]
@willrea no, libtgl is LGPL V2+

> This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

**Comment by willrea** [comment]
@majn Well damn, how did I miss the "Lesser" in there? Well, since you have the option to use it under LGPLv3 there should be no problem once openssl is relicensed under Apache v2

**Comment by majn** [comment]
Just to keep track of the most obvious issues involved when porting to windows:

using <unistd.h> and <fctnl.h> is portable across Unices, but no further. Should have used <stdio.h> instead.
The case configuration path contains "+49176...". NTFS doesn't allow + in paths, I believe. Pidgin logs are stored in a "%29176..." folder, I think this should be viable for telegram-purple itself, too.
Don't rely on /dev/urandom (and stop treating /dev/random like it's a better source! >_<)

**Comment by BenWiederhake** [comment]
Windows already is supported. There's an embarrassing amount of issues with it, but it's supported nevertheless.
