### ISSUE TITLE
Installs on Tails, crashes

### ISSUE THREAD

**Issue by frictionlessmeme** [majn/telegram-purple#61]
Tried installing using the Debian instructions on a Tails live CD instance (most recent release).

Had to add 'gcc' and 'make' packages to the apt-get line.

Everything installs, and the Telegram option comes up in the Add Account dialogue, but when you enter your number and click "Add" Pidgin crashes.

Running pidgin -d > debug.log results in a blank log file.

Symptoms reproducible on different computers using same Live CD.

**Comment by majn** [comment]
> Running pidgin -d > debug.log results in a blank log file.

That's weird, have you tried running it without redirect and checked if there isn't any output?

**Comment by frictionlessmeme** [comment]
Yes, no output. I have been trying to find out if it is a peculiar security feature in Tails. No luck.

**Comment by BenWiederhake** [comment]
First of all, using Tails with Pidgin is probably a bad idea. Please read https://tails.boum.org/doc/about/warning/index.en.html and consult a crypto expert. Nevertheless, a bug is a bug, even when triggered under strange circumstances, like "icons have reddish taint when monitor is burning", so back to topic:

I can still reproduce this issue on Tails 1.6 (i386), the one with SHA256 `6daba429ec9372af0822d8dd4c3e96407240a31c9373173a5985d8d669ea1d00`

Note that tails tries to "workaround" some issue and introduces a bug: arguments to pidgin aren't passed. Change `/usr/local/bin/pidgin` by adding a `$@` at the end of the last line, so that it ends with `pidgin $@`. This doesn't work perfectly, but works well enough with arguments like `-d`

I'll look into it.

**Comment by BenWiederhake** [comment]
Can [reproduce this bug](https://www.dropbox.com/s/mz9w34jw6tyzodb/tails-beta4-fail.png?dl=0) even with the newest, unreleased version. I don't get it.

Brain dump: It fails somewhere in `telegram-base.c#read_pubkey_file`

**Comment by BenWiederhake** [comment]
`open` fails with errno 13 (`EACCES /* Permission denied */`), even though everyone can read the file.

If I write a small program that just calls `open` on the file, it suddenly all works.

This sounds a bit like a `ulimit` issue (and indeed, `ulimit -n` is smaller in tails), but that's not the case (it would cause `errno = 24 /* EMFILE */`).

I'm out of ideas what this could be.

**Comment by BenWiederhake** [comment]
So the reason is apparmor denying the `r` permission. This happens with the filenames `/etc/purple/telegram-server.tglpub` and `/etc/telegram-purple/server.tglpub`. I have no idea how pidgin manages to read it's own configuration at `/etc/purple/prefs.xml`, because it's not mentioned in any file.

However, there is the line `owner @{HOME}/.purple/** rwk`, which means: pidgin is explicitely allowed to read all files in that directory.

This means that `local_install` is the only way to reliably and quickly resolve this issue. Dammit. See #47

**Comment by frictionlessmeme** [comment]
Ah, am I right in saying that local_install now works? I had the same problem as referenced in #47 but haven't tried it since then.

**Comment by BenWiederhake** [comment]
Done, use `make local_install` on Tails.

Please note that the Telegram icon and translations are not available when using `local_install`.

Anyone who is interested in using `make install` on Tails should contact the Tails maintainer who wrote the AppArmor rules for pidgin. These rules are faulty, because they are too strict. For future reference: telegram-purple would need access to these files, when using with pidgin:

    /etc/telegram-purple/server.tglpub (!!!)
    /usr/lib/purple-2/telegram-purple.so
    /usr/share/locale/*/LC_MESSAGES/telegram-purple.mo
    /usr/share/pixmaps/pidgin/protocols/{16,32,48}/telegram.png
    $HOME/.purple/telegram-purple/

The file marked with `(!!!)` seems to be the one that makes most problems with apparmor.
