### ISSUE TITLE
Push messages

### ISSUE THREAD

**Issue by roberth1990** [majn/telegram-purple#77]
Can you please inplement support to push messages? 
Messages I have written and sent with other clients doesn't appear in pidgin.

**Comment by majn** [comment]
This is a bug, it works on all versions I've tested so far. What version of libpurple, telegram-purple and Pidgin do you use?

**Comment by roberth1990** [comment]
I don't remember what version I used last time I tested, I installed 1.0.0beta now and it works, the push message works when pidgin is turned off, or chat window is closed, but it never pushes message history  over and new messages doesn't persist when I close the chat window, can you inplement this?

**Comment by majn** [comment]
So are you saying that the history is entirely gone (when clicking on chat history), or the history doesn't show up in the chat window?

**Comment by roberth1990** [comment]
In the chatwindow. Only what has been said before the pidgin and telegram-purple was installed and logged in the first time after a lot has been said through other clients and that appears only one time, and the next time the chat window has been opened after it was closed it is gone from the chat window, and can only be found when opening the log. That is not the behaviour I want to, I want everything that has been said X number of days back in time always be in the chat window every time I open it after it is closed. Hope this is clear to you.

**Comment by majn** [comment]
I understand, but this is specific Pidgin behavior and has got nothing to do with the libpurple protocol plugin I'm writing. Afaik. there is a Pidgin plugin with this behavior called "history" or something like that, that does exactly what you want.

For fetching old messages, there is an option called (Fetch past history on first login) which fetches all past messages in the extended settings, but its really slow since the Telegram history can get huge and it only works on the very first login on an account.
